# Generated by Django 3.1.7 on 2021-04-05 15:38

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Url')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='Наименование тэга')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Url')),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название тренировки')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Url')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Начало контента')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Продолжение контента')),
                ('image', models.ImageField(blank=True, upload_to='image/%Y/%m/%d/', verbose_name='Фото/изображение')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано?')),
            ],
            options={
                'verbose_name': 'Тренировка',
                'verbose_name_plural': 'Тренировки',
            },
        ),
        migrations.CreateModel(
            name='ContentPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h1', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок1')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Url')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Начало контента')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Продолжение контента')),
                ('image', models.ImageField(blank=True, upload_to='image/%Y/%m/%d/', verbose_name='Фото/изображение')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано?')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Имя автроа поста')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='blog_app.category', verbose_name='Категория')),
                ('tag', models.ManyToManyField(blank=True, related_name='posts', to='blog_app.Tag', verbose_name='Тэг')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-created_at'],
            },
        ),
    ]
