# Generated by Django 3.1.7 on 2021-04-06 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title'], 'verbose_name': 'Категория(ю)', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='workoutpost',
            options={'verbose_name': 'Тренировка(у)', 'verbose_name_plural': 'Тренировки'},
        ),
        migrations.AlterField(
            model_name='contentpost',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
    ]
